apiVersion: v1
kind: Service
metadata:
  name: sc-nfs-nginx
  labels:
    app: sc-nginx
spec:
  type: NodePort
  selector:
    app: sc-nginx
  ports:
    - protocol: TCP
      targetPort: 80
      port: 80
      nodePort: 30183
